do $$
begin
    if pg_get_serial_sequence('members', 'id') is null then
        alter table members alter column id add generated by default as identity;
    end if;

    if pg_get_serial_sequence('rooms', 'id') is null then
        alter table rooms alter column id add generated by default as identity;
    end if;

    if pg_get_serial_sequence('room_members', 'id') is null then
        alter table room_members alter column id add generated by default as identity;
    end if;

    if pg_get_serial_sequence('room_invitations', 'id') is null then
        alter table room_invitations alter column id add generated by default as identity;
    end if;
end $$;
